services:
  embedding:
    build:
      context: .
    environment:
      - HOSTNAME=localhost
      - TOKENIZATION_WORKERS=1
    scale: 1
    ports:
      - 80
    volumes:
      - model:/data

volumes:
  model:
