services:
  embedding:
    build:
      context: .
    environment:
      - HOSTNAME=0.0.0.0
      - TOKENIZATION_WORKERS=1
    scale: 1
    ports:
      - 8080:80
    volumes:
      - model:/data

volumes:
  model:
