services:
  embedding:
    build:
      context: .
    environment:
      - HOSTNAME=0.0.0.0
      - TOKENIZATION_WORKERS=1
      - MODEL_ID=jinaai/jina-embeddings-v2-base-en
      - REVISION=refs/heads/main
    scale: 1
    ports:
      - 8080:80
    volumes:
      - model:/data

volumes:
  model:
